import Head from 'next/head'
import * as React from 'react'
import { Inter } from 'next/font/google'
import { NextPage } from 'next'
import { css, CSSObject } from '@emotion/react'
import Link from 'next/link'
import { MobileStyle } from '@/styles/mediaQuery'
import { ReactChildren, ReactNode } from 'react'
import { Children } from 'path-scurry'

const inter = Inter({ subsets: ['latin'] })

const HomePage: NextPage = () => {
  return (
    <div css={ContainerCss}>
      {/*<Head>*/}
      {/*  <title>Create Next App</title>*/}
      {/*  <meta name="description" content="Generated by create next app" />*/}
      {/*  <meta name="viewport" content="width=device-width, initial-scale=1" />*/}
      {/*  <link rel="icon" href="/favicon.ico" />*/}
      {/*</Head>*/}
      <div>
        <div className="logo-area">로고이미지</div>
        <div className="menu">
          <Link href={'/projects'}>Projects</Link>
          <Link href={'/contact'}>Contact</Link>
          <button>다크모드</button>
        </div>
      </div>
      <div className="contents">
        <p className="title">저입니다</p>
        <p className="desc">
          설명 머라머라머라 <br /> 설명 머라머라머라 <br /> 설명 머라머라머라
        </p>
        <Link href={'/projects'}>궁금하면 눌러요</Link>
      </div>
    </div>
  )
}

export default HomePage

export const ContainerCss = css`
  font-size: 20px;

  ${MobileStyle(
    css(`
      font-size: 12px;
  `)
  )}
`
